window.CLIENT_CONFIG = {

  property: {
    name: 'Blue Waves Beach Stay',
    tagline: 'Your soulful escape by the sea',
    location: 'Kadle Beach, Holangadde, Kumta, Uttara Kannada, Karnataka 581351',
    phone: '+91 70192 55618',
    email: 'bluewavesbeachstay@gmail.com',
    currency: 'INR',
    price_per_night: 700,
    max_guests: 10,
    description: 'A welcoming beachfront sanctuary perched beside the pristine Kadle Beach in Kumta. Choose from cosy double rooms with sea breezes, air-conditioned superior rooms, a magical tent stay under the stars, or our wallet-friendly 10-bed dormitory — all just footsteps from the Arabian Sea.',
    contact_widget: {
      whatsapp_enabled: true,
      whatsapp_number: '917019255618',
      call_enabled: true,
      call_number: '+91 70192 55618',
    },
  },

  photos: [
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16608/1660833/1660833984/photo-blue-waves-beach-stay-kumta-1.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16608/1660837/1660837200/photo-blue-waves-beach-stay-kumta-2.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16672/1667211/1667211718/photo-blue-waves-beach-stay-kumta-3.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16606/1660669/1660669461/photo-blue-waves-beach-stay-kumta-4.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16606/1660669/1660669485/photo-blue-waves-beach-stay-kumta-5.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16640/1664048/1664048559/photo-blue-waves-beach-stay-kumta-6.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16640/1664048/1664048042/photo-blue-waves-beach-stay-kumta-7.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16640/1664048/1664048574/photo-blue-waves-beach-stay-kumta-8.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16608/1660835/1660835877/photo-blue-waves-beach-stay-kumta-9.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16640/1664048/1664048053/photo-blue-waves-beach-stay-kumta-10.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16640/1664048/1664048054/photo-blue-waves-beach-stay-kumta-11.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16640/1664048/1664048056/photo-blue-waves-beach-stay-kumta-12.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16640/1664048/1664048567/photo-blue-waves-beach-stay-kumta-13.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16608/1660835/1660835786/photo-blue-waves-beach-stay-kumta-14.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16640/1664048/1664048040/photo-blue-waves-beach-stay-kumta-16.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16606/1660652/1660652332/photo-blue-waves-beach-stay-kumta-17.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16606/1660652/1660652355/photo-blue-waves-beach-stay-kumta-18.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16640/1664048/1664048024/photo-blue-waves-beach-stay-kumta-19.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16608/1660833/1660833867/photo-blue-waves-beach-stay-kumta-20.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16640/1664048/1664048555/photo-blue-waves-beach-stay-kumta-21.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16640/1664048/1664048564/photo-blue-waves-beach-stay-kumta-22.JPEG',
    'https://www.in-karnataka.com/data/Photos/OriginalPhoto/16640/1664048/1664048457/photo-blue-waves-beach-stay-kumta-23.JPEG',
  ],

  rooms: [
    {
      id: 'superior-double-ac',
      name: 'Superior Double Room (AC)',
      bed: 'Double Bed',
      size: '20 m²',
      max_guests: 2,
      total: 4,
      price: 1800,
      desc: 'Our best rooms — air-conditioned with a private en-suite bathroom, dining area, and sea views right from your window. Comes with a double bed, wardrobe, flat-screen TV, and complimentary toiletries. Perfect for couples wanting comfort by Kadle Beach.',
      amenities: [
        { icon: 'fa-wifi',      label: 'Free WiFi' },
        { icon: 'fa-snowflake', label: 'Air Conditioning' },
        { icon: 'fa-shower',    label: 'Private Bathroom' },
        { icon: 'fa-water',     label: 'Sea View' },
        { icon: 'fa-tv',        label: 'Flat-screen TV' },
      ],
      perks: [
        { label: 'Sea View',             cls: 'blue',  icon: 'fa-water' },
        { label: 'Breakfast Available',  cls: 'green', icon: 'fa-mug-hot' },
        { label: 'Free Cancellation',    cls: 'blue',  icon: 'fa-rotate-left' },
      ],
      photos: [
        'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=900&q=80',
        'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=900&q=80',
        'https://images.unsplash.com/photo-1560185127-6a00e8553a0d?w=900&q=80',
      ],
    },
    {
      id: 'double-room',
      name: 'Double Room',
      bed: 'Double Bed',
      size: '18 m²',
      max_guests: 2,
      total: 3,
      price: 1500,
      desc: 'A clean, breezy room with sea views, private bathroom with shower, wardrobe, and dining area. The sea air keeps it naturally cool — great value for budget-conscious travellers who want a private room steps from the beach.',
      amenities: [
        { icon: 'fa-wifi',    label: 'Free WiFi' },
        { icon: 'fa-fan',     label: 'Ceiling Fan' },
        { icon: 'fa-shower',  label: 'Private Bathroom' },
        { icon: 'fa-water',   label: 'Sea View' },
        { icon: 'fa-shirt',   label: 'Wardrobe' },
      ],
      perks: [
        { label: 'Sea View',             cls: 'blue',  icon: 'fa-water' },
        { label: 'Breakfast Available',  cls: 'green', icon: 'fa-mug-hot' },
        { label: 'Free Cancellation',    cls: 'blue',  icon: 'fa-rotate-left' },
      ],
      photos: [
        'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=900&q=80',
        'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=900&q=80',
        'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=900&q=80',
      ],
    },
    {
      id: 'starlight-tent',
      name: 'Starlight Tent Stay',
      bed: 'Double Bed',
      size: 'Beachside',
      max_guests: 2,
      total: 6,
      price: 1000,
      desc: 'Sleep under the stars with the sound of waves as your lullaby. Each beach tent is set up with a comfortable double bed — wake up to a golden sunrise over the Arabian Sea. Shared bathrooms are clean and nearby. An experience, not just an accommodation.',
      amenities: [
        { icon: 'fa-wifi',           label: 'Free WiFi' },
        { icon: 'fa-shower',         label: 'Shared Bathrooms' },
        { icon: 'fa-umbrella-beach', label: 'Steps to Beach' },
        { icon: 'fa-fire',           label: 'Campfire Evenings' },
        { icon: 'fa-star',           label: 'Stargazing' },
      ],
      perks: [
        { label: 'Beachside Location', cls: 'blue',  icon: 'fa-umbrella-beach' },
        { label: 'Campfire Evenings',  cls: 'gold',  icon: 'fa-fire' },
        { label: 'Free Cancellation',  cls: 'blue',  icon: 'fa-rotate-left' },
      ],
      photos: [
        'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=900&q=80',
        'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=900&q=80',
        'https://images.unsplash.com/photo-1519046904884-53103b34b206?w=900&q=80',
      ],
    },
    {
      id: 'mixed-dormitory',
      name: '10-Bed Mixed Dormitory',
      bed: '10 Bunk Beds',
      size: 'Shared',
      max_guests: 10,
      total: 1,
      price: 700,
      desc: 'The most budget-friendly way to stay by Kadle Beach. A clean, secure dormitory with ten bunk beds — ideal for solo travellers and backpacking groups. Shared bathrooms, free WiFi, personal storage, and direct beach access just outside.',
      amenities: [
        { icon: 'fa-wifi',    label: 'Free WiFi' },
        { icon: 'fa-shower',  label: 'Shared Bathrooms' },
        { icon: 'fa-lock',    label: 'Personal Storage' },
        { icon: 'fa-fan',     label: 'Ceiling Fan' },
        { icon: 'fa-users',   label: 'Common Area' },
      ],
      perks: [
        { label: 'Budget Friendly',      cls: 'green', icon: 'fa-indian-rupee-sign' },
        { label: 'Breakfast Available',  cls: 'green', icon: 'fa-mug-hot' },
        { label: 'Free Cancellation',    cls: 'blue',  icon: 'fa-rotate-left' },
      ],
      photos: [
        'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=900&q=80',
        'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=900&q=80',
        'https://images.unsplash.com/photo-1559599101-f09722fb4948?w=900&q=80',
      ],
    },
  ],

  reviews: {
    rating: 4.2,
    total: 89,
    source: 'google',
    reviews: [
      { author: 'Vikram Pai',      location: 'Mangaluru',  date: 'March 2024',    rating: 5, text: 'Exactly what I was looking for — budget-friendly stay right on Kadle Beach. The tent stay was magical. Woke up to waves and had the whole beach to ourselves at sunrise.' },
      { author: 'Divya Sharma',    location: 'Bengaluru',  date: 'February 2024', rating: 4, text: 'Stayed in the superior double room. Clean, comfortable, and the sea views from the window were lovely. Staff was helpful. Property is literally steps from the beach — great value.' },
      { author: 'Arjun Bhat',      location: 'Pune',       date: 'January 2024',  rating: 4, text: 'Used the dormitory for our backpacking group. Super clean, good WiFi, secure storage. Owner is friendly and gave great local tips. Kadle Beach is quiet and beautiful.' },
      { author: 'Meera Krishnan',  location: 'Chennai',    date: 'December 2023', rating: 5, text: 'Solo trip, tent stay — one of the best decisions I\'ve made. Bonfire in the evening, stars overhead, waves nearby. Absolutely unforgettable. Will definitely come back!' },
      { author: 'Rahul Fernandes', location: 'Goa',        date: 'November 2023', rating: 4, text: 'Good honest property at a fair price. The double room was breezy and comfortable. Kadle Beach is peaceful and far less crowded than Gokarna. Perfect for a quiet escape.' },
    ],
  },

};
